# Change these first
owner: UnstoppableSwap # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Download Site
    url: https://unstoppableswap.net/
  - name: Documentation Site
    url: https://unstoppableswap.net/
  - name: Public Registry API
    url: https://api.unstoppableswap.net/api/list
  - name: Public Rendezvous Point
    url: discover.unstoppableswap.net
    port: 8888
    check: "tcp-ping"

assignees: # Users to assign downtime issues (optional)
  - binarybaron
  - einliterflasche
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.unstoppableswap.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: UnstoppableSwap
  introTitle: "This is the uptime monitor and status page for everything related to UnstoppableSwap."
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
